import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {MainContext} from '../contexts/MainContext'
import {MainHome} from '../templates/MainHome'
import {Drawer} from '../search/Drawer'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainContext>
        <MainHome />
        <Drawer />
      </MainContext>
    </div>
  )
}

export default Home
